{
 "title": "aio-health-service-dp",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": "${VAR_COMPONENT}" },
   { "name": "component_text", "query": "${VAR_COMPONENT_TEXT}" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   {
    "name": "aio_dp_self_test_pipeline",
    "query": "${VAR_AIO_DP_SELF_TEST_PIPELINE}"
   },
   { "name": "latency_percentile", "query": "${VAR_LATENCY_PERCENTILE}" },
   { "name": "latency_quantile_range", "query": "5m,10m,15m,1h,3h,6h,24h" },
   { "name": "aio_dp_error_threshold", "query": "${VAR_AIO_DP_ERROR_THRESHOLD}" },
   {
    "name": "aio_dp_nats_utilization_threshold",
    "query": "${VAR_AIO_DP_NATS_UTILIZATION_THRESHOLD}"
   },
   {
    "name": "aio_dp_latency_threshold_ms",
    "query": "${VAR_AIO_DP_LATENCY_THRESHOLD_MS}"
   },
   { "name": "aio_dp_error_rate", "query": "${VAR_AIO_DP_ERROR_RATE}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - ${component_text} Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Stage Count and Reference Data</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stage counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aio_dp_stage_info{cluster=\"$cluster\"}) by (stage_type) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RefData Enrichment Latency",
   "type": "timeseries",
   "description": "Enrichment latency broken down by pipeline, over interval",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_enrich_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (pipeline_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enriched Message Count",
   "type": "stat",
   "description": "Total count of enriched messages across the cluster\n\nTODO: Make count / interval (tbd)",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_dp_enrich_latency_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refdata Store Count",
   "type": "stat",
   "description": "Unique refdata stores\n\nTodo: get dataset names",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(enrich_datasetid, cluster) (aio_dp_refdata_global_store_get_latency_count{cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Scenario Health (SLO/RUM) related to ${component_text}</span>\n</div>\n"
   }
  },
  {
   "title": "SLOs",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(\r\n        (\r\n            1 - min(\r\n                sgn(sum(rate(aio_dp_stage_errors{cluster=~\"$cluster\"}[$__rate_interval])) <= $aio_dp_error_threshold)\r\n                or\r\n                sgn(sum(rate(aio_dp_reader_errors{cluster=~\"$cluster\"}[$__rate_interval])) <= $aio_dp_error_threshold)\r\n            )\r\n            or vector(1)\r\n        )\r\n        ,\"_\",\"Errors\",\"\",\"\") \r\n    or\r\n    label_replace(\r\n        (\r\n            sgn(\r\n                (\r\n                    sum(rate(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval])) + \r\n                    sum(rate(aio_dp_stage_errors{cluster=\"$cluster\"}[$__rate_interval]))\r\n                ) / \r\n                (\r\n                    sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) + \r\n                    sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]))\r\n                ) < $aio_dp_error_rate\r\n            )\r\n            or vector(1)\r\n        )\r\n        ,\"_\",\"Success Rate\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n        (min(\r\n            sgn(\r\n                max(\r\n                    histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    ) < $aio_dp_latency_threshold_ms\r\n                )\r\n            or\r\n            1 - sgn(\r\n                    max(\r\n                        histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    ) >= $aio_dp_latency_threshold_ms\r\n                )\r\n        ) \r\n        or vector(404))\r\n        ,\"_\",\"Pipeline Latency\",\"\",\"\")\r\n    or        \r\n    label_replace(\r\n        (\r\n            min(\r\n                sgn(\r\n                    sum(rate(aio_dp_reader_processed_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_incoming_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                )\r\n                or\r\n                sgn(\r\n                    sum(rate(aio_dp_stage_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_processed_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                )\r\n            )\r\n            or vector(404))\r\n    ,\"_\",\"Heartbeats\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n        (\r\n            sgn(\r\n                sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"}) > 0\r\n                and\r\n                (sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"}) / \r\n                sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"}))\r\n                <= $aio_dp_nats_utilization_threshold\r\n            )\r\n        or vector(404))\r\n    ,\"_\",\"Message Store\",\"\",\"\")\r\n),\"_\",\"SLO Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "#label_replace(min(\r\n    label_replace(\r\n        (\r\n            1 - min(\r\n                sgn(sum(rate(aio_dp_stage_errors{cluster=~\"$cluster\"}[$__rate_interval])) <= $aio_dp_error_threshold)\r\n                or\r\n                sgn(sum(rate(aio_dp_reader_errors{cluster=~\"$cluster\"}[$__rate_interval])) <= $aio_dp_error_threshold)\r\n            )\r\n            or vector(1)\r\n        )\r\n        ,\"_\",\"Errors\",\"\",\"\") \r\n    or\r\n    label_replace(\r\n        (\r\n            sgn(\r\n                (\r\n                    sum(rate(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval])) + \r\n                    sum(rate(aio_dp_stage_errors{cluster=\"$cluster\"}[$__rate_interval]))\r\n                ) / \r\n                (\r\n                    sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) + \r\n                    sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]))\r\n                ) < $aio_dp_error_rate\r\n            )\r\n            or vector(1)\r\n        )\r\n        ,\"_\",\"Success Rate\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n        (min(\r\n            sgn(\r\n                max(\r\n                    histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    ) < $aio_dp_latency_threshold_ms\r\n                )\r\n            or\r\n            1 - sgn(\r\n                    max(\r\n                        histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    ) >= $aio_dp_latency_threshold_ms\r\n                )\r\n        ) \r\n        or vector(404))\r\n        ,\"_\",\"Pipeline Latency\",\"\",\"\")\r\n    or        \r\n    label_replace(\r\n        (\r\n            min(\r\n                sgn(\r\n                    sum(rate(aio_dp_reader_processed_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_incoming_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                )\r\n                or\r\n                sgn(\r\n                    sum(rate(aio_dp_stage_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_processed_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))\r\n                )\r\n            )\r\n            or vector(404))\r\n    ,\"_\",\"Heartbeats\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n        (\r\n            sgn(\r\n                sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"}) > 0\r\n                and\r\n                (sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"}) / \r\n                sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"}))\r\n                <= $aio_dp_nats_utilization_threshold\r\n            )\r\n        or vector(404))\r\n    ,\"_\",\"Message Store\",\"\",\"\")\r\n#),\"_\",\"SLO Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Pipeline Internal Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(histogram_quantile(0.95, sum(rate(aio_dp_pipeline_internal_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le, cloud_resource_id))[$__range:])",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "NATS Message Store Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(max(100*\r\n    sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"})\r\n    / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"})\r\n    ),\"_\",\"Max Utilization\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Messages and Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "    label_replace(\r\n            max(round(rate(aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\"}[$__rate_interval])*60))\r\n        ,\"_\",\"Output (msgs/min)\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n            0 < round(sum(increase(aio_dp_stage_errors{cluster=~\"$cluster\"}[$__rate_interval])) + sum(rate(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval])))\r\n        ,\"_\",\"Error rate\",\"\",\"\")\r\n    or\r\n    vector(0) > 0",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Number of Pipelines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cloud_resource_id, cluster) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Number of Incoming Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Service Health (Synthetics/Self-test)</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (min(\r\n            label_replace(aio_mq_connect_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"connect\",\"\",\"\") or\r\n            label_replace(aio_mq_ping_correctness{cluster=~\"$cluster\"},\"depHealth\",\"ping\",\"\",\"\") or\r\n            label_replace(aio_mq_publish_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"publish\",\"\",\"\") or\r\n            label_replace(aio_mq_subscribe_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"subscribe\",\"\",\"\") or\r\n            label_replace(aio_mq_unsubscribe_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"unsubscribe\",\"\",\"\") or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/e2e98c97-7655-44d1-b8f3-5008b7f6ffbb/aio-health-service-mq\",\"\",\"\")\r\n        ,\"_\",\"Self-test input (MQ)\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_dp_stage_errors{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test stage errors\",\"\",\"\") or\r\n    label_replace(\r\n        (min(sgn(rate(\r\n            aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval]\r\n            )*60)) or vector(-1))\r\n        ,\"_\",\"Self-test output\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) < $aio_dp_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) >= $aio_dp_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test pipeline latency\",\"\",\"\") or \r\n    label_replace(label_replace(\r\n        (min(\r\n            0 * sgn(max(\r\n                100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"})\r\n                / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"})\r\n                ) > 90) or\r\n            1 * sgn(max(\r\n                100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"})\r\n                / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"})\r\n                ) <= 90) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/e17d0b7f-9771-4cb8-adf9-56cbaef3fff6/aio-service-dp-messagestore\",\"\",\"\")\r\n        ,\"_\",\"Store Utilization\",\"\",\"\") or \r\n    vector(0)>0\r\n),\"_\",\"Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "# label_replace(min(\r\n    label_replace(label_replace(\r\n        (min(\r\n            label_replace(aio_mq_connect_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"connect\",\"\",\"\") or\r\n            label_replace(aio_mq_ping_correctness{cluster=~\"$cluster\"},\"depHealth\",\"ping\",\"\",\"\") or\r\n            label_replace(aio_mq_publish_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"publish\",\"\",\"\") or\r\n            label_replace(aio_mq_subscribe_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"subscribe\",\"\",\"\") or\r\n            label_replace(aio_mq_unsubscribe_route_replication_correctness{cluster=~\"$cluster\"},\"depHealth\",\"unsubscribe\",\"\",\"\") or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/e2e98c97-7655-44d1-b8f3-5008b7f6ffbb/aio-health-service-mq\",\"\",\"\")\r\n        ,\"_\",\"Self-test input (MQ)\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_dp_stage_errors{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test stage errors\",\"\",\"\") or\r\n    label_replace(\r\n        (min(sgn(rate(\r\n            aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval]\r\n            )*60)) or vector(-1))\r\n        ,\"_\",\"Self-test output\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) < $aio_dp_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) >= $aio_dp_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test pipeline latency\",\"\",\"\") or \r\n    label_replace(label_replace(\r\n        (min(\r\n            0 * sgn(max(\r\n                100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"})\r\n                / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"})\r\n                ) > 90) or\r\n            1 * sgn(max(\r\n                100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=~\"$cluster\"})\r\n                / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=~\"$cluster\"})\r\n                ) <= 90) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/e17d0b7f-9771-4cb8-adf9-56cbaef3fff6/aio-service-dp-messagestore\",\"\",\"\")\r\n        ,\"_\",\"Store Utilization\",\"\",\"\") or \r\n    vector(0)>0\r\n# ),\"_\",\"Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Self-test Output and Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "    label_replace(#label_replace(\r\n        #(min(sgn(\r\n            max(round(rate(\r\n            aio_dp_stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval]\r\n            )*60))#)) or vector(-1))\r\n        #,\"url\",\"/d/f46e5384-d78d-480a-911c-0328cb20b224/e4k-ping\",\"\",\"\")\r\n        ,\"_\",\"Self-test output (msgs/min)\",\"\",\"\") or\r\n    #stage_incoming_messages{cluster=~\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"} or\r\n    label_replace(\r\n        #0 * sgn(\r\n            0 < round(sum(increase(aio_dp_stage_errors{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval])))#) or\r\n            #or vector(3)\r\n        ,\"_\",\"Self-test error rate\",\"\",\"\") or\r\n    vector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Self-test Pipeline Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    max(histogram_quantile(0.95, rate(\r\n    aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n    )))\r\n    ,\"_\",\"Self-test pipeline latency\",\"\",\"\") or\r\nlabel_replace($aio_dp_latency_threshold_ms * sgn(\r\n    max(histogram_quantile(0.95, rate(\r\n    aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n    )))\r\n    ),\"_\",\"Self-test latency threshold\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n    max(histogram_quantile(0.95, rate(\r\n    aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n    ))) >= $aio_dp_latency_threshold_ms\r\n    ,\"x\",\"Over threshold\",\"\",\"\")\r\n    ,\"_\",\"Self-test pipeline latency over threshold\",\"\",\"\") or\r\nlabel_replace(vector(0),\"_\",\"hidden-timeline\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Golden Metrics</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage/Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "label_replace(#quantile_over_time($latency_percentile,\r\n    sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]))\r\n    #[$latency_quantile_range:])\r\n    ,\"_\",\"Input (msgs/sec)\",\"\",\"\") or\r\nlabel_replace(#quantile_over_time($latency_percentile,\r\n    sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\"}[$__rate_interval]))\r\n    #[$latency_quantile_range:])\r\n    ,\"_\",\"Output (msgs/sec)\",\"\",\"\") or\r\nlabel_replace(\r\n    count(count by (cloud_resource_id, runner_partition) (rate(aio_dp_runner_info{cluster=\"$cluster\"}[$__rate_interval])))\r\n    ,\"_\",\"Runners (count)\",\"\",\"\") or\r\nlabel_replace(\r\n    count(count by (cloud_resource_id, stage_id) (rate(aio_dp_stage_info{cluster=\"$cluster\"}[$__rate_interval])))\r\n    ,\"_\",\"Stages (count)\",\"\",\"\") or\r\n# label_replace(vector(1),\"_\",\"TODO: Usage/Volume\",\"\",\"\") or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate/Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    (  (sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) > 0 or vector(0))\r\n      / (sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) > 0 or vector(1))\r\n    ) and\r\n        (sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\"}[$__rate_interval])) > 0)\r\n    or  \r\n    (  (sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) > 0 or vector(0))\r\n      / (sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval])) > 0 or vector(1))\r\n    ) >0 and\r\n        (sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\"}[$__rate_interval])) == 0) * 0\r\n    ,\"_\",\".Success Rate\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(rate(aio_dp_stage_errors{cluster=\"$cluster\"}[$__rate_interval])) or vector(0)\r\n    ,\"_\",\"Stage Errors\",\"\",\"\") or\r\nlabel_replace(\r\nsum(rate(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval])) or vector(0)\r\n    ,\"_\",\"Reader Errors\",\"\",\"\") or\r\n#label_replace(vector(1),\"_\",\"TODO: Success Rate\",\"\",\"\") or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "#ping_latency_last_value_ms{cluster=\"$cluster\"} or\r\nmax by (_)(\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id!~\"$aio_dp_self_test_pipeline\"}[$latency_quantile_range])) by (le))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"RUM Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$latency_quantile_range])) by (le,cloud_resource_id))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Worst Pipeline Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, rate(aio_dp_pipeline_latency_bucket{cluster=~\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$latency_quantile_range]))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Self-test Pipeline Latency $1\",\"pout\",\"(.*)\") or\r\n    vector(0)>0) or\r\n#label_replace(vector(1),\"_\",\"TODO: Latency\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "description": "No saturation data available for ${component:text}",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "expr": "#max by(_)(\r\n#label_replace(clamp( # NOTE: data for percent is really choppy; need to clamp, take rate over longer window (and offset), and then \r\n#    # truncate to zero when no backpressure is detected in the $__rate_interval to get a less noisy, more accurate view of percentage\r\n#    sum(rate(backpressure_packets_rejected{pod_type=\"BE\", cluster=~\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m)) * 100 / \r\n#    sum(rate(publishes_received{pod_type=\"FE\", cluster=~\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m))\r\n#    and sum(rate(backpressure_packets_rejected{pod_type=\"BE\", cluster=~\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])) > 0 or vector(0)\r\n#    ,0,100),\"_\",\"Backpressure Rejection %\",\"\",\"\") or\r\n#label_replace(sum by(short_hostname)(\r\n#    label_replace(\r\n#        sum by(hostname) (ceil(rate(backpressure_packets_rejected{cluster=~\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])*60))\r\n#        ,\"short_hostname\", \"$1\", \"hostname\", \"(.*).azedge-dmqtt-backend.*\"))\r\n#    ,\"_\",\"# rejected by $1\",\"short_hostname\",\"(.*)\") > 0 or\r\n#    vector(0)>0\r\n#) or\r\n#label_replace(vector(0),\"_\",\"TODO: Saturation\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Infrastructure Workload Health</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(0),\"_\",\"Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"Container Restart Health\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"cpu\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"Container CPU Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace, container)\r\n    ) >= .95) - 0.5 # show health state of 0.5 if container memory utilization >= 95%\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"Container Memory health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum ( # by(workloadType) (\r\n#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")\r\n#  / label_replace(label_join(\r\n#        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n#    label_replace(label_join(\r\n#        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n#  / label_replace(label_join(\r\n  label_replace(sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n    ),\"_\",\"Requested\",\"\",\"\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} \r\n      - kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n      kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} \r\n    - kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n      kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\") # this is to zero if no workloads of this type exist\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"} \r\n      - kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor \r\nlabel_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m])*60)[1h:])),\"_\",\"restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n# Percent of containers with limits defined\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}) /\r\n    count(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",cpu=\"total\"}) *100\r\n    ,\"_\",\"Percent containers with CPU Limits (%)\",\"\",\"\")\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 47 },
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n# Percent containers with limits\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"}) /\r\n    count(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}) *100\r\n    ,\"_\",\"Percent containers with Memory Limits (%)\",\"\",\"\")\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)\r\n##(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) < 0.2,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\")) # Show milli-cores if rate below 0.2 cores\r\n# CPU Time (cores version, if >= 0.2 cores)\r\n##or (label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval])),\"_\",\"CPU Usage (cores)\",\"\",\"\") \r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) >= 0.2,\"_\",\"CPU Usage (cores)\",\"\",\"\")) # Show in cores if rate at or above 0.2 cores\r\n# Shows the max in millicores, used to determine which is shown (commented out for UX; only uncomment to debug above)\r\n#or label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:])*1000,\"_\",\"CPU Usage (milli-cores) MAX\",\"\",\"\")\r\n# Sum of all limits defined, in Cores\r\n##or label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}),\"_\",\"CPU Limits (cores)\",\"\",\"\")\r\n# CPU Throttling:\r\n##or label_replace(100*(max(\r\n##        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(pod)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)\") or #,\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"pod\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# Memory working bytes\r\nmax by(pod)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Errors & Logs</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 10 Kube Events entries (from $cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents\r\n| where TimeGenerated > $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| where ClusterName == '$cluster'\r\n| where Name matches regex '${component:raw}'\r\n//| order by TimeGenerated desc\r\n| order by LastSeen desc, FirstSeen desc, TimeGenerated desc\r\n| project-rename PodName = Name\r\n| project FirstSeen, LastSeen, Count, PodName, Reason, Message\r\n| take 10",
      "resources": [
       "/subscriptions/af342bf1-1ace-41df-902c-47921400551b"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp ${component_text}-specific</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 100 Log entries (from $cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerLogV2\r\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| where _ResourceId contains '$cluster'\r\n| where ContainerName contains \"dp\"\r\n| order by TimeGenerated desc\r\n| project TimeGenerated, PodName, ContainerName, LogSource, LogMessage\r\n| take 100",
      "resources": [
       "/subscriptions/af342bf1-1ace-41df-902c-47921400551b"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}