{
 "title": "aio-service-dp-runner",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aio_dp_runner_info,cloud_resource_id)"
    }
   },
   {
    "name": "partitionId",
    "label": "Partition ID",
    "query": {
     "query": "label_values(aio_dp_runner_info,runner_partition)"
    }
   },
   { "name": "runnerMessageTraceId", "label": "Runner Message Trace ID" },
   { "name": "runnerInitTraceId" }
  ]
 },
 "panels": [
  {
   "title": "Input Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_outgoing_messages{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", stage_id=\"$$input\", runner_partition=\"$partitionId\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "E2E Latency (95th Percentile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aio_dp_runner_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}",
     "legendFormat": "{{runner_state}}"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aio_dp_runner_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\", }",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Stage Throughputs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(stage_id, stage_type, stage_name, stage_index) (increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__range])) * on(stage_id) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(stage_id, stage_type, stage_name, stage_index) (increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__range])) * on(stage_id) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(stage_id, stage_type, stage_name, stage_index) (increase(aio_dp_stage_errors{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__range])) * on(stage_id) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Latencies",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time((histogram_quantile(0.50, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((avg(rate(aio_dp_stage_latency_sum{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]) / rate(aio_dp_stage_latency_count{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (stage_id, stage_type, stage_name, stage_index) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner E2E Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Source Stage Blocked by Upstream",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_dp_runner_input_stage_blocked_time_ratio_bucket{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Stage and Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "sum by(stage_id, stage_type, error_code) (rate(aio_dp_stage_errors{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", runner_partition=\"$partitionId\"}[$__rate_interval]))",
     "legendFormat": "{{error_code}}: {{stage_id}} ({{stage_type}})"
    }
   ]
  }
 ]
}