{
 "title": "aio-health-infra-cluster",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   { "name": "nodeThresholdRed", "query": "${VAR_NODETHRESHOLDRED}" },
   { "name": "nodeThresholdYellow", "query": "${VAR_NODETHRESHOLDYELLOW}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - Infrastructure Cluster Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Node Health</span>\n</div>\n"
   }
  },
  {
   "title": "Node Ready Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "# Node Health Status\r\n####################\r\n# RED (0) if no nodes ready without pressure\r\n# YELLOW (0.5) if at least one node not ready or with pressure\r\n# Green (1.0) otherwise\r\n#label_replace(\r\nmax by (node) (kube_node_status_condition{cluster=~\"$cluster\",condition=\"ready\",status=\"false\"} > 0) * 0 or\r\nmax by (node) (kube_node_status_condition{cluster=~\"$cluster\",condition!=\"ready\",status=\"true\"} > 0) * 0.5 or\r\nmax by (node) (kube_node_status_condition{cluster=~\"$cluster\",condition=\"ready\",status=\"true\"} > 0) * 1\r\n#) / sum(kube_node_info)#  ,\"_\",\"Node Health\",\"\",\"\")\r\n#or label_replace(sum(kube_node_info),\"_\",\"Node Total Count\",\"\",\"\")\r\n#or label_replace(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace( sum(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"}),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(sum(sgn(\r\n#   max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"})\r\n# + max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})\r\n#  )),\"_\",\"Unhealthy Node Count\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Ready Health Issue Details",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "expr": "# Node Health Details\r\n####################\r\nlabel_replace(sum (kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"true\"}),\"_\",\"# Ready\",\"\",\"\") or\r\nmax by(_)(label_replace(label_join(\r\n  label_replace(max by (node,condition) (kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}), \"condition\",\"Not Ready\",\"\",\"\") > 0\r\n  or max by (node,condition) (kube_node_status_condition{cluster=~\"$cluster\",condition!=\"Ready\",status=\"true\"}) > 0\r\n  ,\"_\",\":\",\"condition\",\"node\")\r\n  ,\"_\",\"$1($2)\",\"_\",\"([^:]*):(.*)\")\r\n) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "#############################\r\n# Node CPU Health\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_cpu_seconds_total{cluster=~\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=~\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Node CPU Usage Pecent\r\nmax by (_) (label_replace(\r\n  100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n        + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n  ) * 100)\r\n  #* on (instance) group_left(node) label_replace(max by(internal_ip,node) (kube_node_info),\"instance\",\"$1:9100\",\"internal_ip\",\"(.*)\") # Node Info\r\n  ,\"_\",\"$1\",\"instance\",\"(.*)\")\r\n)\r\nor label_replace(vector($nodeThresholdRed),\"_\",\"Unhealthy\",\"\",\"\")\r\nor label_replace(vector($nodeThresholdYellow),\"_\",\"Warning\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "#############################\r\n# Node Memory Health\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - (node_memory_MemFree_bytes{cluster=~\"$cluster\"} + node_memory_Buffers_bytes{cluster=~\"$cluster\"} + node_memory_Cached_bytes{cluster=~\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=~\"$cluster\"})) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - (node_memory_MemFree_bytes{cluster=~\"$cluster\"} + node_memory_Buffers_bytes{cluster=~\"$cluster\"} + node_memory_Cached_bytes{cluster=~\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=~\"$cluster\"})) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_memory_MemTotal_bytes{cluster=~\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=~\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Node Memory Usage Pecent\r\nmin by (_) (label_replace(\r\n  (100 * sum by (instance)\r\n    (node_memory_MemTotal_bytes{cluster=\"$cluster\"} \r\n    - node_memory_MemFree_bytes{cluster=\"$cluster\"} \r\n    - node_memory_Buffers_bytes{cluster=\"$cluster\"} \r\n    - node_memory_Cached_bytes{cluster=\"$cluster\"}) \r\n  / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"}))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\")\r\n)\r\nor label_replace(vector($nodeThresholdRed),\"_\",\"Unhealthy\",\"\",\"\")\r\nor label_replace(vector($nodeThresholdYellow),\"_\",\"Warning\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "#############################\r\n# Disk Usage Health\r\nmin by(node)(label_replace(vector(0)>0\r\n  or 0.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=~\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=~\"$cluster\"}) > 10) > $nodeThresholdRed)\r\n  or 0.5 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=~\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=~\"$cluster\"}) > 10) > $nodeThresholdYellow)\r\n  or 1.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=~\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=~\"$cluster\"})))\r\n,\"node\",\"$1\",\"instance\",\"(.*)\"))\r\nor max by (node) (kube_node_info{cluster=\"$cluster\"}) * -1 # Baseline by node",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Disk Usage\r\nmax by(_) (label_replace(label_join(\r\n  max by (node,device) (label_replace(\r\n    min by(instance,device) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10)\r\n      ,\"node\",\"$1\",\"instance\",\"(.*)\")\r\n  ),\"nodeDevice\",\",\",\"node\",\"device\")\r\n  ,\"_\",\"$1($2)\",\"nodeDevice\",\"^([^,]+)[,](.*)$\")\r\n)\r\nor label_replace(vector($nodeThresholdRed),\"_\",\"Unhealthy\",\"\",\"\")\r\nor label_replace(vector($nodeThresholdYellow),\"_\",\"Warning\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "# How to use this dashboard\nThis dashboard highlights cluster-level health signals that may\naffect Azure Edge Services health and is broken down into the\nfollowing sections:\n\n#### Node health\nThis section breaks down Node health starting with Node \nReadiness/pressure signals to health by resource.  The left side\nshows basic health signal where YELLOW and RED indicate when a node\nhas crossed corresponding thresholds.  The right side provides a \nmore detailed view behind the health signal shown on the left.\n"
   }
  }
 ]
}