{
 "title": "aio-service-dp-pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aio_dp_runner_info,cloud_resource_id)"
    }
   },
   { "name": "runnerMessageTraceId", "label": "Runner Message Trace ID" },
   { "name": "runnerInitTraceId", "label": "Runner Init Trace ID" },
   { "name": "readerMessageTraceId", "label": "Reader Message Trace ID" }
  ]
 },
 "panels": [
  { "title": "Reader Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Written to Message Store",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_processed_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reader Latency (95th Percentile)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aio_dp_reader_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runner Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Stage Throughputs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum((increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range]))) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range]))) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((increase(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range]))) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Latencies",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time((histogram_quantile(0.50, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Throughputs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$$input\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_type=~\"^output/.*$\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner E2E Latencies",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time((histogram_quantile(0.50, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Stage and Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (stage_id, stage_type, error_code)",
     "legendFormat": "{{error_code}}: {{stage_id}} ({{stage_type}})"
    }
   ]
  },
  {
   "title": "Errors by Runner and Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (message_partition_key, error_code)",
     "legendFormat": "{{error_code}}: {{stage_id}} ({{stage_type}})"
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\", cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "err/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "sum(rate(aio_dp_reader_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "E2E Latency (95th Percentile)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runner Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (runner_partition) (rate(aio_dp_runner_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stage Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (stage_id) (rate(aio_dp_stage_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incomplete checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Checkpointing Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_runner_checkpoint_error{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cloud_resource_id) (aio_dp_runner_checkpoint_size{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}